### PR TITLE
New Appveyor Scripts with publishing support

### PR DESCRIPTION
**Pull request by BergWerkGIS**
refs #39

AppVeyor passes: 
https://ci.appveyor.com/project/Mapbox/node-osmium/build/1.0.44

TODO:
* add S3 credentials @springmeyer who should add them?

### CODE REVIEW

**Comment by springmeyer** [comment]
> add S3 credentials @springmeyer who should add them?

Will do now.

**Comment by springmeyer** [comment]
done, let me know if those work.

**Comment by BergWerkGIS** [comment]
@springmeyer nope: https://ci.appveyor.com/project/Mapbox/node-osmium/build/1.0.47#L407

**Comment by springmeyer** [comment]
closing per https://github.com/osmcode/node-osmium/issues/76#issuecomment-219138676

**Pull request closed without merging**
