### PR TITLE
Fix #111

### LINKED ISSUE #111: Won't build on node 12
Shifted to Ubuntu 20.04, so thought I'd get myself up to date with Node 12 (current LTS). Then remembered I had this problem before - node-osmium won't build on Node 12 because v8 has [deprecated lots of non-maybe APIs](https://github.com/joyeecheung/node/blob/v8-maybe-doc/CPP_STYLE_GUIDE.md#use-maybe-version-of-v8-apis).

```
mat@devbox:~/dev$ git clone https://github.com/osmcode/node-osmium.git
Cloning into 'node-osmium'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 2548 (delta 4), reused 7 (delta 2), pack-reused 2534
Receiving objects: 100% (2548/2548), 604.51 KiB | 1.42 MiB/s, done.
Resolving deltas: 100% (1806/1806), done.
mat@devbox:~/dev$ cd node-osmium
mat@devbox:~/dev/node-osmium$ make
npm install node-pre-gyp
npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-pre-gyp@0.10.3
added 66 packages from 25 contributors and audited 66 packages in 4.607s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm install `node -e "console.log(Object.keys(require('./package.json').dependencies).join(' '))"` \
`node -e "console.log(Object.keys(require('./package.json').devDependencies).join(' '))"` --clang=1
npm WARN deprecated turf-difference@2.0.0: Turf packages are now namespaced: please use @turf/difference instead
npm WARN deprecated geojson-normalize@0.0.0: This module is now under the @mapbox namespace: install @mapbox/geojson-normalize instead
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
+ aws-sdk@2.720.0
+ nan@2.14.1
+ geojson-coords@0.0.0
+ turf-difference@2.0.0
+ node-pre-gyp@0.10.3
+ mocha@2.5.3
+ wellknown@0.4.2
+ osm-testdata@1.0.0
added 59 packages from 372 contributors, updated 8 packages and audited 125 packages in 9.863s

1 package is looking for funding
  run `npm fund` for details

found 9 vulnerabilities (7 low, 1 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
./node_modules/.bin/node-pre-gyp configure --loglevel=error --clang=1
./node_modules/.bin/node-pre-gyp build --loglevel=error --clang=1
make[1]: Entering directory '/home/mat/dev/node-osmium/build'
  CXX(target) Release/obj.target/osmium/src/apply.o
In file included from ../src/apply.cpp:6:
../node_modules/nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../node_modules/nan/nan.h:2294:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2294 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from ../src/apply.cpp:22:
../src/utils.hpp: In function ‘v8::Local<v8::Object> node_osmium::new_external(Args&& ...)’:
../src/utils.hpp:38:13: error: ‘Handle’ is not a member of ‘v8’
   38 |         v8::Handle<v8::Value> ext = Nan::New<v8::External>(new T(std::forward<Args>(args)...));
      |             ^~~~~~
../src/utils.hpp:38:29: error: expected primary-expression before ‘>’ token
   38 |         v8::Handle<v8::Value> ext = Nan::New<v8::External>(new T(std::forward<Args>(args)...));
      |                             ^
../src/utils.hpp:38:31: error: ‘ext’ was not declared in this scope; did you mean ‘exit’?
   38 |         v8::Handle<v8::Value> ext = Nan::New<v8::External>(new T(std::forward<Args>(args)...));
      |                               ^~~
      |                               exit
../src/utils.hpp:41:68: error: no matching function for call to ‘v8::Object::ToObject()’
   41 |         return scope.Escape(maybe_local.ToLocalChecked()->ToObject());
      |                                                                    ^
In file included from /home/mat/.cache/node-gyp/12.18.3/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:56,
                 from ../src/apply.cpp:6:
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
 2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
      |                                            ^~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/mat/.cache/node-gyp/12.18.3/include/node/v8-internal.h:14,
                 from /home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:27,
                 from /home/mat/.cache/node-gyp/12.18.3/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:56,
                 from ../src/apply.cpp:6:
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
 2686 |                 Local<Object> ToObject(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
 2686 |                 Local<Object> ToObject(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/apply.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_osmium::apply(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/apply.cpp:164:46: error: no matching function for call to ‘v8::Value::ToObject()’
  164 |                 auto obj = info[i]->ToObject();
      |                                              ^
In file included from /home/mat/.cache/node-gyp/12.18.3/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:56,
                 from ../src/apply.cpp:6:
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
 2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
      |                                            ^~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/mat/.cache/node-gyp/12.18.3/include/node/v8-internal.h:14,
                 from /home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:27,
                 from /home/mat/.cache/node-gyp/12.18.3/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:56,
                 from ../src/apply.cpp:6:
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
 2686 |                 Local<Object> ToObject(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
 2686 |                 Local<Object> ToObject(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/apply.cpp:175:49: error: no matching function for call to ‘v8::Value::ToObject()’
  175 |                 auto source = info[0]->ToObject();
      |                                                 ^
In file included from /home/mat/.cache/node-gyp/12.18.3/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:56,
                 from ../src/apply.cpp:6:
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
 2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
      |                                            ^~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/mat/.cache/node-gyp/12.18.3/include/node/v8-internal.h:14,
                 from /home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:27,
                 from /home/mat/.cache/node-gyp/12.18.3/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:56,
                 from ../src/apply.cpp:6:
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
 2686 |                 Local<Object> ToObject(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
 2686 |                 Local<Object> ToObject(Isolate* isolate) const);
      |                               ^~~~~~~~
/home/mat/.cache/node-gyp/12.18.3/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
make[1]: *** [osmium.target.mk:137: Release/obj.target/osmium/src/apply.o] Error 1
make[1]: Leaving directory '/home/mat/dev/node-osmium/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--loglevel=error" "--clang=1" "--module=/home/mat/dev/node-osmium/lib/binding/osmium.node" "--module_name=osmium" "--module_path=/home/mat/dev/node-osmium/lib/binding" "--napi_version=6" "--node_abi_napi=napi"
gyp ERR! cwd /home/mat/dev/node-osmium
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --loglevel=error --clang=1 --module=/home/mat/dev/node-osmium/lib/binding/osmium.node --module_name=osmium --module_path=/home/mat/dev/node-osmium/lib/binding --napi_version=6 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/mat/dev/node-osmium/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.4.0-42-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/mat/dev/node-osmium/node_modules/.bin/node-pre-gyp" "build" "--loglevel=error" "--clang=1"
node-pre-gyp ERR! cwd /home/mat/dev/node-osmium
node-pre-gyp ERR! node -v v12.18.3
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --loglevel=error --clang=1 --module=/home/mat/dev/node-osmium/lib/binding/osmium.node --module_name=osmium --module_path=/home/mat/dev/node-osmium/lib/binding --napi_version=6 --node_abi_napi=napi' (1)
make: *** [Makefile:31: build-all] Error 1
mat@devbox:~/dev/node-osmium$
```

Appreciate there are no binaries for Node 12 (#108), but it would be nice if it compiled.

### PR DESCRIPTION
**Pull request by matburnham**
Fixes #111 to build with Node 12 and Node 14.

### CODE REVIEW

**Comment by matburnham** [comment]
Notwithstanding #114 this seems to pass all tests and works with the code I was originally trying to use with Node 12. Travis-CI passes except for Node 4 which was already broken.

**Comment by awendt** [comment]
@springmeyer @joto Can we please get this merged?

Also, will you accept a pull request that removes unsupported NodeJS versions? (i.e. v4, v6, and v8)

**Comment by springmeyer** [comment]
@awendt I'm no longer in a position where I have time to do releases or test them. This one in particular might get the code to compile but it would require testing to ensure it runs correctly. Also, the right solution here is to port to NAPI, but that is a big effort. So, I must ask, would you or @matburnham be able to accomplish what you are trying to do with osmium-tool instead of node-osmium?

**Comment by awendt** [comment]
@springmeyer Thanks for the heads-up!

I have been using `node-osmium` for a script that checks the Haversine distance for each way and drops the ones that are shorter than a threshold. From the docs, I don't see how this can be easily replaced with `osmium-tool` but I'm sure I can find a way.

**Comment by joto** [comment]
Thanks for the PR. I am sorry it took so long to get it merged. Unfortunately node-osmium is at the bottom of my priority list and it always takes me some time to come around to it.

**Pull request merged**
